// Mocks generated by Mockito 5.4.6 from annotations
// in staffsync/test/mock/attendance_repository_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:staffsync/domain/model/attendance.model.dart' as _i4;
import 'package:staffsync/domain/repositories/attendance.repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AttendanceRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAttendanceRepository extends _i1.Mock
    implements _i2.AttendanceRepository {
  MockAttendanceRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.Attendance>> getAttendances(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getAttendances, [token]),
            returnValue: _i3.Future<List<_i4.Attendance>>.value(
              <_i4.Attendance>[],
            ),
          )
          as _i3.Future<List<_i4.Attendance>>);

  @override
  _i3.Future<void> checkIn(_i4.AttendanceResponse? attendanceResponse) =>
      (super.noSuchMethod(
            Invocation.method(#checkIn, [attendanceResponse]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> checkOut(_i4.AttendanceResponse? attendanceResponse) =>
      (super.noSuchMethod(
            Invocation.method(#checkOut, [attendanceResponse]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteAttendance(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAttendance, [id]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
