// Mocks generated by Mockito 5.4.6 from annotations
// in staffsync/test/mock/user_repository_mock.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:staffsync/domain/model/notification.model.dart' as _i5;
import 'package:staffsync/domain/model/user.model.dart' as _i2;
import 'package:staffsync/domain/repositories/user.repository.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUser_0 extends _i1.SmartFake implements _i2.User {
  _FakeUser_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserRepository extends _i1.Mock implements _i3.UserRepository {
  MockUserRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.User> getCurrUser(int? id, String? endpoint) =>
      (super.noSuchMethod(
            Invocation.method(#getCurrUser, [id, endpoint]),
            returnValue: _i4.Future<_i2.User>.value(
              _FakeUser_0(
                this,
                Invocation.method(#getCurrUser, [id, endpoint]),
              ),
            ),
          )
          as _i4.Future<_i2.User>);

  @override
  _i4.Future<List<_i2.User>> getEmployees(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#getEmployees, [token]),
            returnValue: _i4.Future<List<_i2.User>>.value(<_i2.User>[]),
          )
          as _i4.Future<List<_i2.User>>);

  @override
  _i4.Future<void> deleteEmployee(int? id, String? token) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmployee, [id, token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteNotification() =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> changePassword({
    required int? userId,
    required String? oldPassword,
    required String? newPassword,
    required String? token,
    required String? endpoint,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #userId: userId,
              #oldPassword: oldPassword,
              #newPassword: newPassword,
              #token: token,
              #endpoint: endpoint,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.NotificationModel>> getNotificationMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationMessage, []),
            returnValue: _i4.Future<List<_i5.NotificationModel>>.value(
              <_i5.NotificationModel>[],
            ),
          )
          as _i4.Future<List<_i5.NotificationModel>>);

  @override
  _i4.Future<void> editProfile(
    int? id,
    String? fullName,
    String? designation,
    String? email,
    String? employmentType,
    String? profilePicture,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editProfile, [
              id,
              fullName,
              designation,
              email,
              employmentType,
              profilePicture,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
